# Generated by Django 4.0.6 on 2022-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
        ('product', '0002_alter_product_options_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
