# Generated by Django 4.0.6 on 2022-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='تصویر'),
        ),
    ]
