# Generated by Django 4.0.6 on 2022-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email_address', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=120, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس های کاربران',
                'db_table': 'contact_us',
            },
        ),
    ]
