# Generated by Django 4.0.6 on 2022-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='copy_right',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
